baseurl = "https://example.org/"
title = "Annie Stein"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

theme = 'hugo-creative-portfolio-theme'

relativeURLs = true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = "Annie's Portfolio"
  copyright = "&copy;2022 Annie Stein"
  sidebarAbout = [
    "Hi, I'm Annie. I'm from the cold fjords of the north, but I like to think I have a warm heart. I'm a lifelong student, and an aspiring artist and designer. I make worlds in my freetime, and stories to go in them. Right now, I'm telling the story of an alternate version of our solar system; the science fantasy world of Solaris. I also write the Morning Realm, a classical fantasy world that marries the nostalgic escapism of youth with the sensitivity of the present."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "anemartestein@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Illustration Gallery"
  url = "https://ko-fi.com/nniee/gallery/"

  [[params.navlinks]]
  name = "Morning Realm"
  url = "https://www.worldanvil.com/w/the-morning-realm-nnie"

  [[params.navlinks]]
  name = "Solaris"
  url = "https://www.worldanvil.com/w/solaris-nnie"

  [params.social]
  email         = "anemartestein@gmail.com"
  twitter       = "https://twitter.com/nniemancy"
